home:
  path: /
  controller: App\Controller\HomeController::index
  #index c'est une m√©thode qu'on appelle sur la classe HomeController
  #ici en haut, c'est une rout et on fixe le chemin


#index:
#    path: /
#    controller: App\Controller\DefaultController::index
